name: mpc_tutorial

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - pip
  - ipykernel
  - jupyterlab
  - notebook
  - nbclient

  # Scientific Python
  - numpy<2
  - scipy
  - matplotlib
  - osqp

  # Robotics / OCP stack
  - mim-solvers=0.2.0
  - crocoddyl=3.2.0
  - pinocchio=3.8.0
  - pinocchio-python=3.8.0
  - libpinocchio=3.8.0
  - coal=3.0.1
  - coal-python=3.0.1
  - libcoal=3.0.1

  # Optional, if used by examples
  - pybullet