name: colab_test
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  # - crocoddyl
  # - pinocchio
  - mim-solvers
  - osqp
  - ipython
  - jupyterlab
  - ffmpeg